#! /usr/bin/bash
#
# Copyright (c) 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

bats_require_minimum_version 1.5.0


setup() {
}


teardown_suite() {

}
