name: 1cp3worker-mgmt
provider: libvirt
headless: true
controlPlaneNodes: 1
kubernetesVersion: 1.30
providers:
  libvirt:
    controlPlaneNode:
      cpu: 3
      memory: 10000000K
      storage: 30G
