name: byo-3worker-ipv6
provider: byo
workerNodes: 3
virtualIp: 2001:db8:ca2:3::d6
podSubnet: 2001:db8:0f01::/48
serviceSubnet: 2001:db8:0f02::/108
providers:
  byo:
    networkInterface: enp1s0
    automaticTokenCreation: true
